# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_panel.ui',
# licensing of 'settings_panel.ui' applies.
#
# Created: Wed Jan 22 19:31:30 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(619, 510)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabJson = QtWidgets.QWidget()
        self.tabJson.setObjectName("tabJson")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabJson)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetLab = QtWidgets.QWidget(self.tabJson)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetLab.sizePolicy().hasHeightForWidth())
        self.widgetLab.setSizePolicy(sizePolicy)
        self.widgetLab.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetLab.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetLab.setObjectName("widgetLab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetLab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelLab = QtWidgets.QLabel(self.widgetLab)
        self.labelLab.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelLab.setFont(font)
        self.labelLab.setObjectName("labelLab")
        self.horizontalLayout_3.addWidget(self.labelLab)
        self.textboxLab = QtWidgets.QLineEdit(self.widgetLab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxLab.setFont(font)
        self.textboxLab.setFrame(False)
        self.textboxLab.setObjectName("textboxLab")
        self.horizontalLayout_3.addWidget(self.textboxLab)
        self.verticalLayout.addWidget(self.widgetLab)
        self.widgetExperimenter = QtWidgets.QWidget(self.tabJson)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetExperimenter.sizePolicy().hasHeightForWidth())
        self.widgetExperimenter.setSizePolicy(sizePolicy)
        self.widgetExperimenter.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetExperimenter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetExperimenter.setObjectName("widgetExperimenter")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetExperimenter)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelExperimenter = QtWidgets.QLabel(self.widgetExperimenter)
        self.labelExperimenter.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelExperimenter.setFont(font)
        self.labelExperimenter.setObjectName("labelExperimenter")
        self.horizontalLayout_2.addWidget(self.labelExperimenter)
        self.textboxExperimenter = QtWidgets.QLineEdit(self.widgetExperimenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxExperimenter.setFont(font)
        self.textboxExperimenter.setFrame(False)
        self.textboxExperimenter.setObjectName("textboxExperimenter")
        self.horizontalLayout_2.addWidget(self.textboxExperimenter)
        self.verticalLayout.addWidget(self.widgetExperimenter)
        self.widgetDatasetName = QtWidgets.QWidget(self.tabJson)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetDatasetName.sizePolicy().hasHeightForWidth())
        self.widgetDatasetName.setSizePolicy(sizePolicy)
        self.widgetDatasetName.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetDatasetName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetDatasetName.setObjectName("widgetDatasetName")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetDatasetName)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelDatasetName = QtWidgets.QLabel(self.widgetDatasetName)
        self.labelDatasetName.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelDatasetName.setFont(font)
        self.labelDatasetName.setObjectName("labelDatasetName")
        self.horizontalLayout.addWidget(self.labelDatasetName)
        self.textboxDatasetName = QtWidgets.QLineEdit(self.widgetDatasetName)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxDatasetName.setFont(font)
        self.textboxDatasetName.setFrame(False)
        self.textboxDatasetName.setObjectName("textboxDatasetName")
        self.horizontalLayout.addWidget(self.textboxDatasetName)
        self.verticalLayout.addWidget(self.widgetDatasetName)
        self.widgetInstitutionAddress = QtWidgets.QWidget(self.tabJson)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetInstitutionAddress.sizePolicy().hasHeightForWidth())
        self.widgetInstitutionAddress.setSizePolicy(sizePolicy)
        self.widgetInstitutionAddress.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetInstitutionAddress.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetInstitutionAddress.setObjectName("widgetInstitutionAddress")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetInstitutionAddress)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelInstitutionAddress = QtWidgets.QLabel(self.widgetInstitutionAddress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.labelInstitutionAddress.sizePolicy().hasHeightForWidth())
        self.labelInstitutionAddress.setSizePolicy(sizePolicy)
        self.labelInstitutionAddress.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelInstitutionAddress.setFont(font)
        self.labelInstitutionAddress.setObjectName("labelInstitutionAddress")
        self.horizontalLayout_5.addWidget(self.labelInstitutionAddress)
        self.textboxInstitutionAddress = QtWidgets.QLineEdit(self.widgetInstitutionAddress)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxInstitutionAddress.setFont(font)
        self.textboxInstitutionAddress.setFrame(False)
        self.textboxInstitutionAddress.setObjectName("textboxInstitutionAddress")
        self.horizontalLayout_5.addWidget(self.textboxInstitutionAddress)
        self.verticalLayout.addWidget(self.widgetInstitutionAddress)
        self.widgetInstitutionName = QtWidgets.QWidget(self.tabJson)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetInstitutionName.sizePolicy().hasHeightForWidth())
        self.widgetInstitutionName.setSizePolicy(sizePolicy)
        self.widgetInstitutionName.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetInstitutionName.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetInstitutionName.setObjectName("widgetInstitutionName")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetInstitutionName)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelInstitutionName = QtWidgets.QLabel(self.widgetInstitutionName)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.labelInstitutionName.sizePolicy().hasHeightForWidth())
        self.labelInstitutionName.setSizePolicy(sizePolicy)
        self.labelInstitutionName.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelInstitutionName.setFont(font)
        self.labelInstitutionName.setObjectName("labelInstitutionName")
        self.horizontalLayout_4.addWidget(self.labelInstitutionName)
        self.textboxInstitutionName = QtWidgets.QLineEdit(self.widgetInstitutionName)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxInstitutionName.setFont(font)
        self.textboxInstitutionName.setFrame(False)
        self.textboxInstitutionName.setObjectName("textboxInstitutionName")
        self.horizontalLayout_4.addWidget(self.textboxInstitutionName)
        self.verticalLayout.addWidget(self.widgetInstitutionName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tabJson, "")
        self.tabElectrodeInfo = QtWidgets.QWidget()
        self.tabElectrodeInfo.setObjectName("tabElectrodeInfo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabElectrodeInfo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labeliEEG = QtWidgets.QLabel(self.tabElectrodeInfo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labeliEEG.setFont(font)
        self.labeliEEG.setObjectName("labeliEEG")
        self.verticalLayout_2.addWidget(self.labeliEEG)
        self.widgetIEEGManufacturer = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetIEEGManufacturer.sizePolicy().hasHeightForWidth())
        self.widgetIEEGManufacturer.setSizePolicy(sizePolicy)
        self.widgetIEEGManufacturer.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetIEEGManufacturer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetIEEGManufacturer.setObjectName("widgetIEEGManufacturer")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widgetIEEGManufacturer)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelIEEGManufacturer = QtWidgets.QLabel(self.widgetIEEGManufacturer)
        self.labelIEEGManufacturer.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelIEEGManufacturer.setFont(font)
        self.labelIEEGManufacturer.setIndent(20)
        self.labelIEEGManufacturer.setObjectName("labelIEEGManufacturer")
        self.horizontalLayout_6.addWidget(self.labelIEEGManufacturer)
        self.textboxIEEGManufacturer = QtWidgets.QLineEdit(self.widgetIEEGManufacturer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxIEEGManufacturer.setFont(font)
        self.textboxIEEGManufacturer.setFrame(False)
        self.textboxIEEGManufacturer.setObjectName("textboxIEEGManufacturer")
        self.horizontalLayout_6.addWidget(self.textboxIEEGManufacturer)
        self.verticalLayout_2.addWidget(self.widgetIEEGManufacturer)
        self.widgetIEEGType = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetIEEGType.sizePolicy().hasHeightForWidth())
        self.widgetIEEGType.setSizePolicy(sizePolicy)
        self.widgetIEEGType.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetIEEGType.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetIEEGType.setObjectName("widgetIEEGType")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widgetIEEGType)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelIEEGType = QtWidgets.QLabel(self.widgetIEEGType)
        self.labelIEEGType.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelIEEGType.setFont(font)
        self.labelIEEGType.setIndent(20)
        self.labelIEEGType.setObjectName("labelIEEGType")
        self.horizontalLayout_7.addWidget(self.labelIEEGType)
        self.textboxIEEGType = QtWidgets.QLineEdit(self.widgetIEEGType)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxIEEGType.setFont(font)
        self.textboxIEEGType.setFrame(False)
        self.textboxIEEGType.setObjectName("textboxIEEGType")
        self.horizontalLayout_7.addWidget(self.textboxIEEGType)
        self.verticalLayout_2.addWidget(self.widgetIEEGType)
        self.widgetIEEGMaterial = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetIEEGMaterial.sizePolicy().hasHeightForWidth())
        self.widgetIEEGMaterial.setSizePolicy(sizePolicy)
        self.widgetIEEGMaterial.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetIEEGMaterial.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetIEEGMaterial.setObjectName("widgetIEEGMaterial")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widgetIEEGMaterial)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelIEEGMaterial = QtWidgets.QLabel(self.widgetIEEGMaterial)
        self.labelIEEGMaterial.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelIEEGMaterial.setFont(font)
        self.labelIEEGMaterial.setIndent(20)
        self.labelIEEGMaterial.setObjectName("labelIEEGMaterial")
        self.horizontalLayout_8.addWidget(self.labelIEEGMaterial)
        self.textboxIEEGMaterial = QtWidgets.QLineEdit(self.widgetIEEGMaterial)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxIEEGMaterial.setFont(font)
        self.textboxIEEGMaterial.setFrame(False)
        self.textboxIEEGMaterial.setObjectName("textboxIEEGMaterial")
        self.horizontalLayout_8.addWidget(self.textboxIEEGMaterial)
        self.verticalLayout_2.addWidget(self.widgetIEEGMaterial)
        self.widgetIEEGDiameter = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetIEEGDiameter.sizePolicy().hasHeightForWidth())
        self.widgetIEEGDiameter.setSizePolicy(sizePolicy)
        self.widgetIEEGDiameter.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetIEEGDiameter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetIEEGDiameter.setObjectName("widgetIEEGDiameter")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widgetIEEGDiameter)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelIEEGDiameter = QtWidgets.QLabel(self.widgetIEEGDiameter)
        self.labelIEEGDiameter.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelIEEGDiameter.setFont(font)
        self.labelIEEGDiameter.setIndent(20)
        self.labelIEEGDiameter.setObjectName("labelIEEGDiameter")
        self.horizontalLayout_9.addWidget(self.labelIEEGDiameter)
        self.textboxIEEGDiameter = QtWidgets.QLineEdit(self.widgetIEEGDiameter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxIEEGDiameter.setFont(font)
        self.textboxIEEGDiameter.setFrame(False)
        self.textboxIEEGDiameter.setObjectName("textboxIEEGDiameter")
        self.horizontalLayout_9.addWidget(self.textboxIEEGDiameter)
        self.verticalLayout_2.addWidget(self.widgetIEEGDiameter)
        self.labelEEG = QtWidgets.QLabel(self.tabElectrodeInfo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelEEG.setFont(font)
        self.labelEEG.setObjectName("labelEEG")
        self.verticalLayout_2.addWidget(self.labelEEG)
        self.widgetEEGManufacturer = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetEEGManufacturer.sizePolicy().hasHeightForWidth())
        self.widgetEEGManufacturer.setSizePolicy(sizePolicy)
        self.widgetEEGManufacturer.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetEEGManufacturer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetEEGManufacturer.setObjectName("widgetEEGManufacturer")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widgetEEGManufacturer)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelEEGManufacturer = QtWidgets.QLabel(self.widgetEEGManufacturer)
        self.labelEEGManufacturer.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelEEGManufacturer.setFont(font)
        self.labelEEGManufacturer.setIndent(20)
        self.labelEEGManufacturer.setObjectName("labelEEGManufacturer")
        self.horizontalLayout_17.addWidget(self.labelEEGManufacturer)
        self.textboxEEGManufacturer = QtWidgets.QLineEdit(self.widgetEEGManufacturer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxEEGManufacturer.setFont(font)
        self.textboxEEGManufacturer.setFrame(False)
        self.textboxEEGManufacturer.setObjectName("textboxEEGManufacturer")
        self.horizontalLayout_17.addWidget(self.textboxEEGManufacturer)
        self.verticalLayout_2.addWidget(self.widgetEEGManufacturer)
        self.widgetEEGType = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetEEGType.sizePolicy().hasHeightForWidth())
        self.widgetEEGType.setSizePolicy(sizePolicy)
        self.widgetEEGType.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetEEGType.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetEEGType.setObjectName("widgetEEGType")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widgetEEGType)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelEEGType = QtWidgets.QLabel(self.widgetEEGType)
        self.labelEEGType.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelEEGType.setFont(font)
        self.labelEEGType.setIndent(20)
        self.labelEEGType.setObjectName("labelEEGType")
        self.horizontalLayout_16.addWidget(self.labelEEGType)
        self.textboxEEGType = QtWidgets.QLineEdit(self.widgetEEGType)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxEEGType.setFont(font)
        self.textboxEEGType.setFrame(False)
        self.textboxEEGType.setObjectName("textboxEEGType")
        self.horizontalLayout_16.addWidget(self.textboxEEGType)
        self.verticalLayout_2.addWidget(self.widgetEEGType)
        self.widgetEEGMaterial = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetEEGMaterial.sizePolicy().hasHeightForWidth())
        self.widgetEEGMaterial.setSizePolicy(sizePolicy)
        self.widgetEEGMaterial.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetEEGMaterial.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetEEGMaterial.setObjectName("widgetEEGMaterial")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widgetEEGMaterial)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelEEGMaterial = QtWidgets.QLabel(self.widgetEEGMaterial)
        self.labelEEGMaterial.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelEEGMaterial.setFont(font)
        self.labelEEGMaterial.setIndent(20)
        self.labelEEGMaterial.setObjectName("labelEEGMaterial")
        self.horizontalLayout_14.addWidget(self.labelEEGMaterial)
        self.textboxEEGMaterial = QtWidgets.QLineEdit(self.widgetEEGMaterial)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxEEGMaterial.setFont(font)
        self.textboxEEGMaterial.setFrame(False)
        self.textboxEEGMaterial.setObjectName("textboxEEGMaterial")
        self.horizontalLayout_14.addWidget(self.textboxEEGMaterial)
        self.verticalLayout_2.addWidget(self.widgetEEGMaterial)
        self.widgetEEGDiameter = QtWidgets.QWidget(self.tabElectrodeInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.widgetEEGDiameter.sizePolicy().hasHeightForWidth())
        self.widgetEEGDiameter.setSizePolicy(sizePolicy)
        self.widgetEEGDiameter.setMinimumSize(QtCore.QSize(0, 40))
        self.widgetEEGDiameter.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widgetEEGDiameter.setObjectName("widgetEEGDiameter")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widgetEEGDiameter)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelEEGDiameter = QtWidgets.QLabel(self.widgetEEGDiameter)
        self.labelEEGDiameter.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.labelEEGDiameter.setFont(font)
        self.labelEEGDiameter.setIndent(20)
        self.labelEEGDiameter.setObjectName("labelEEGDiameter")
        self.horizontalLayout_15.addWidget(self.labelEEGDiameter)
        self.textboxEEGDiameter = QtWidgets.QLineEdit(self.widgetEEGDiameter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textboxEEGDiameter.setFont(font)
        self.textboxEEGDiameter.setFrame(False)
        self.textboxEEGDiameter.setObjectName("textboxEEGDiameter")
        self.horizontalLayout_15.addWidget(self.textboxEEGDiameter)
        self.verticalLayout_2.addWidget(self.widgetEEGDiameter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabElectrodeInfo, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBoxJson = QtWidgets.QDialogButtonBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.buttonBoxJson.setFont(font)
        self.buttonBoxJson.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxJson.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxJson.setObjectName("buttonBoxJson")
        self.verticalLayout_3.addWidget(self.buttonBoxJson)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBoxJson, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBoxJson, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Settings", None, -1))
        self.labelLab.setText(QtWidgets.QApplication.translate("Dialog", "Lab", None, -1))
        self.labelExperimenter.setText(QtWidgets.QApplication.translate("Dialog", "Experimenter", None, -1))
        self.labelDatasetName.setText(QtWidgets.QApplication.translate("Dialog", "Dataset Name", None, -1))
        self.labelInstitutionAddress.setText(QtWidgets.QApplication.translate("Dialog", "Institution Address", None, -1))
        self.labelInstitutionName.setText(QtWidgets.QApplication.translate("Dialog", "Institution Name", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabJson), QtWidgets.QApplication.translate("Dialog", "Json Metadata", None, -1))
        self.labeliEEG.setText(QtWidgets.QApplication.translate("Dialog", "iEEG Electrode Info:", None, -1))
        self.labelIEEGManufacturer.setText(QtWidgets.QApplication.translate("Dialog", "Manufacturer", None, -1))
        self.labelIEEGType.setText(QtWidgets.QApplication.translate("Dialog", "Type", None, -1))
        self.labelIEEGMaterial.setText(QtWidgets.QApplication.translate("Dialog", "Material", None, -1))
        self.labelIEEGDiameter.setText(QtWidgets.QApplication.translate("Dialog", "Diameter", None, -1))
        self.labelEEG.setText(QtWidgets.QApplication.translate("Dialog", "EEG Electrode Info:", None, -1))
        self.labelEEGManufacturer.setText(QtWidgets.QApplication.translate("Dialog", "Manufacturer", None, -1))
        self.labelEEGType.setText(QtWidgets.QApplication.translate("Dialog", "Type", None, -1))
        self.labelEEGMaterial.setText(QtWidgets.QApplication.translate("Dialog", "Material", None, -1))
        self.labelEEGDiameter.setText(QtWidgets.QApplication.translate("Dialog", "Diameter", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabElectrodeInfo), QtWidgets.QApplication.translate("Dialog", "Electrode Info", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

